name: Run Vitest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Instalar dependências
        run: npm i

      - name: Rodar testes com Vitest
        run: npx vitest run --coverage
